name: Deploy befa to s3  

on:  
  push:  
    branches:  
      - main  

jobs:  
  deploy:  
    runs-on: ubuntu-latest  

    steps:  
    - name: Checkout code  
      uses: actions/checkout@v2  

    - name: Set up Node.js  
      uses: actions/setup-node@v2  
      with:  
        node-version: '23.8.0'  

    - name: Install dependencies  
      run: npm install  

    - name: Build the project  
      run: npm run build  

    - name: Configure AWS Credentials  
      env:  
        AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}  
        AWS_REGION: ${{ secrets.AWS_REGION }}  
      run: |  
        echo "[default]" > ~/.aws/config  
        echo "region = ${AWS_REGION}" >> ~/.aws/config  
        aws sts assume-role --role-arn $AWS_ROLE_ARN --role-session-name github-actions-session \
        --output json > ~/.aws/creds.json  

        export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId < ~/.aws/creds.json)  
        export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey < ~/.aws/creds.json)  
        export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken < ~/.aws/creds.json)  

    - name: Sync to S3  
      run: |  
        aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }} --delete  
